blueprint:
  name: Door Light with Motion and Delay (UI-safe)
  description: >
    Turns on a light when a door opens. Turns it off after an optional
    door-close delay or no-motion delay while the door is open. Motion
    sensor is optional.
  domain: automation

  input:
    door_sensor:
      name: Door Sensor
      selector:
        entity:
          domain: binary_sensor

    motion_sensor:
      name: Motion Sensor (optional)
      default: null
      selector:
        entity:
          domain: binary_sensor

    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light

    door_closed_delay:
      name: Delay After Door Closes (optional)
      default: "00:00:00"
      selector:
        duration:

    no_motion_delay:
      name: No Motion Delay (door open)
      default: "00:03:00"
      selector:
        duration:

mode: restart

trigger:
  - platform: state
    entity_id: !input door_sensor
    to: "on"

action:
  # Turn light on immediately
  - service: light.turn_on
    target: !input light_target

  # Wait until either door closes or motion stops
  - wait_for_trigger:
      - platform: state
        entity_id: !input door_sensor
        to: "off"
      - platform: template
        value_template: >
          {% set motion = blueprint.inputs.motion_sensor %}
          {{ motion is not none and is_state(motion, 'off') }}

  # Door closed path
  - choose:
      - conditions:
          - condition: state
            entity_id: !input door_sensor
            state: "off"
        sequence:
          # Wait for door-closed delay using wait_template
          - wait_template: >
              {% set delay_seconds = blueprint.inputs.door_closed_delay.total_seconds() | int %}
              {% set start = now() %}
              {{ (now() - start).total_seconds() >= delay_seconds }}
          # Check motion sensor before turning off
          - condition: template
            value_template: >
              {% set motion = blueprint.inputs.motion_sensor %}
              {{ motion is none or is_state(motion, 'off') }}

      # Door open + no motion path
      - conditions:
          - condition: template
            value_template: >
              {% set motion = blueprint.inputs.motion_sensor %}
              {{ is_state(blueprint.inputs.door_sensor, 'on') and (motion is none or is_state(motion, 'off')) }}
        sequence:
          # Wait for no-motion delay using wait_template
          - wait_template: >
              {% set delay_seconds = blueprint.inputs.no_motion_delay.total_seconds() | int %}
              {% set start = now() %}
              {{ (now() - start).total_seconds() >= delay_seconds }}

  # Final safety checks
  - condition: state
    entity_id: !input.door_sensor
    state: "off"
  - condition: template
    value_template: >
      {% set motion = blueprint.inputs.motion_sensor %}
      {{ motion is none or is_state(motion, 'off') }}

  # Turn light off
  - service: light.turn_off
    target: !input.light_target
